//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AplicacionEmpresa.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dic_Clientes
    {
        public int cli_idClientePk { get; set; }
        public string cli_nombre { get; set; }
        public bool cli_estado { get; set; }
    }
}
