//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
// 
#pragma warning disable 1591

namespace AplicacionEmpresa.WS_NEPS2 {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="WebService1Soap", Namespace="http://tempuri.org/")]
    public partial class WebService1 : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback RadicarSolicitudBackOfficeOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public WebService1() {
            this.Url = global::AplicacionEmpresa.Properties.Settings.Default.AplicacionEmpresa_WS_NEPS2_WebService1;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event RadicarSolicitudBackOfficeCompletedEventHandler RadicarSolicitudBackOfficeCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/RadicarSolicitudBackOffice", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Salida RadicarSolicitudBackOffice(DTORadicacionSolicitudBackOffice data) {
            object[] results = this.Invoke("RadicarSolicitudBackOffice", new object[] {
                        data});
            return ((Salida)(results[0]));
        }
        
        /// <remarks/>
        public void RadicarSolicitudBackOfficeAsync(DTORadicacionSolicitudBackOffice data) {
            this.RadicarSolicitudBackOfficeAsync(data, null);
        }
        
        /// <remarks/>
        public void RadicarSolicitudBackOfficeAsync(DTORadicacionSolicitudBackOffice data, object userState) {
            if ((this.RadicarSolicitudBackOfficeOperationCompleted == null)) {
                this.RadicarSolicitudBackOfficeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRadicarSolicitudBackOfficeOperationCompleted);
            }
            this.InvokeAsync("RadicarSolicitudBackOffice", new object[] {
                        data}, this.RadicarSolicitudBackOfficeOperationCompleted, userState);
        }
        
        private void OnRadicarSolicitudBackOfficeOperationCompleted(object arg) {
            if ((this.RadicarSolicitudBackOfficeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RadicarSolicitudBackOfficeCompleted(this, new RadicarSolicitudBackOfficeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class DTORadicacionSolicitudBackOffice {
        
        private long numeroSolicitudField;
        
        private System.DateTime fechaSolicitudField;
        
        private System.DateTime fechaServicioField;
        
        private int tipoServicioField;
        
        private int prioridadAtencionField;
        
        private string origenAtencionField;
        
        private Ubicacion ubicacionPacienteField;
        
        private Ips ipsField;
        
        private Identificacion identificacionAfiliadoField;
        
        private string nombresAfiliadoField;
        
        private string apellidosAfiliadoField;
        
        private string emailAfiliadoField;
        
        private int preferenciaRespuestaField;
        
        private string planField;
        
        private int ambitoField;
        
        private Diagnostico[] diagnosticosField;
        
        private GrupoTipoAtencion[] gruposTipoAtencionField;
        
        private ProfesionalSalud profesionalSolicitanteField;
        
        private PersonaSolicitante personaSolicitanteField;
        
        private int origenSolicitudField;
        
        private int direccionamientoSolicitudField;
        
        private bool direccionamientoSolicitudFieldSpecified;
        
        private string direccionamientoSolicitudObservacionField;
        
        private int manejoIntegralSegunGuiaField;
        
        private int tiempoTratamientoField;
        
        private bool direccionamientoSolicitudSpecified1Field;
        
        public DTORadicacionSolicitudBackOffice() {
            this.numeroSolicitudField = ((long)(1));
            this.tipoServicioField = 2;
            this.prioridadAtencionField = 2;
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(typeof(long), "1")]
        public long numeroSolicitud {
            get {
                return this.numeroSolicitudField;
            }
            set {
                this.numeroSolicitudField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime fechaSolicitud {
            get {
                return this.fechaSolicitudField;
            }
            set {
                this.fechaSolicitudField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime fechaServicio {
            get {
                return this.fechaServicioField;
            }
            set {
                this.fechaServicioField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(2)]
        public int tipoServicio {
            get {
                return this.tipoServicioField;
            }
            set {
                this.tipoServicioField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(2)]
        public int prioridadAtencion {
            get {
                return this.prioridadAtencionField;
            }
            set {
                this.prioridadAtencionField = value;
            }
        }
        
        /// <remarks/>
        public string origenAtencion {
            get {
                return this.origenAtencionField;
            }
            set {
                this.origenAtencionField = value;
            }
        }
        
        /// <remarks/>
        public Ubicacion ubicacionPaciente {
            get {
                return this.ubicacionPacienteField;
            }
            set {
                this.ubicacionPacienteField = value;
            }
        }
        
        /// <remarks/>
        public Ips ips {
            get {
                return this.ipsField;
            }
            set {
                this.ipsField = value;
            }
        }
        
        /// <remarks/>
        public Identificacion identificacionAfiliado {
            get {
                return this.identificacionAfiliadoField;
            }
            set {
                this.identificacionAfiliadoField = value;
            }
        }
        
        /// <remarks/>
        public string nombresAfiliado {
            get {
                return this.nombresAfiliadoField;
            }
            set {
                this.nombresAfiliadoField = value;
            }
        }
        
        /// <remarks/>
        public string apellidosAfiliado {
            get {
                return this.apellidosAfiliadoField;
            }
            set {
                this.apellidosAfiliadoField = value;
            }
        }
        
        /// <remarks/>
        public string emailAfiliado {
            get {
                return this.emailAfiliadoField;
            }
            set {
                this.emailAfiliadoField = value;
            }
        }
        
        /// <remarks/>
        public int preferenciaRespuesta {
            get {
                return this.preferenciaRespuestaField;
            }
            set {
                this.preferenciaRespuestaField = value;
            }
        }
        
        /// <remarks/>
        public string plan {
            get {
                return this.planField;
            }
            set {
                this.planField = value;
            }
        }
        
        /// <remarks/>
        public int ambito {
            get {
                return this.ambitoField;
            }
            set {
                this.ambitoField = value;
            }
        }
        
        /// <remarks/>
        public Diagnostico[] diagnosticos {
            get {
                return this.diagnosticosField;
            }
            set {
                this.diagnosticosField = value;
            }
        }
        
        /// <remarks/>
        public GrupoTipoAtencion[] gruposTipoAtencion {
            get {
                return this.gruposTipoAtencionField;
            }
            set {
                this.gruposTipoAtencionField = value;
            }
        }
        
        /// <remarks/>
        public ProfesionalSalud profesionalSolicitante {
            get {
                return this.profesionalSolicitanteField;
            }
            set {
                this.profesionalSolicitanteField = value;
            }
        }
        
        /// <remarks/>
        public PersonaSolicitante personaSolicitante {
            get {
                return this.personaSolicitanteField;
            }
            set {
                this.personaSolicitanteField = value;
            }
        }
        
        /// <remarks/>
        public int origenSolicitud {
            get {
                return this.origenSolicitudField;
            }
            set {
                this.origenSolicitudField = value;
            }
        }
        
        /// <remarks/>
        public int direccionamientoSolicitud {
            get {
                return this.direccionamientoSolicitudField;
            }
            set {
                this.direccionamientoSolicitudField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool direccionamientoSolicitudSpecified {
            get {
                return this.direccionamientoSolicitudFieldSpecified;
            }
            set {
                this.direccionamientoSolicitudFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string direccionamientoSolicitudObservacion {
            get {
                return this.direccionamientoSolicitudObservacionField;
            }
            set {
                this.direccionamientoSolicitudObservacionField = value;
            }
        }
        
        /// <remarks/>
        public int manejoIntegralSegunGuia {
            get {
                return this.manejoIntegralSegunGuiaField;
            }
            set {
                this.manejoIntegralSegunGuiaField = value;
            }
        }
        
        /// <remarks/>
        public int tiempoTratamiento {
            get {
                return this.tiempoTratamientoField;
            }
            set {
                this.tiempoTratamientoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("direccionamientoSolicitudSpecified")]
        public bool direccionamientoSolicitudSpecified1 {
            get {
                return this.direccionamientoSolicitudSpecified1Field;
            }
            set {
                this.direccionamientoSolicitudSpecified1Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Ubicacion {
        
        private int codigoField;
        
        private string descripcionField;
        
        /// <remarks/>
        public int codigo {
            get {
                return this.codigoField;
            }
            set {
                this.codigoField = value;
            }
        }
        
        /// <remarks/>
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.ws.autorizaciones.salud.neps.com.co/tipos")]
    public partial class Radicacion {
        
        private string numeroRadicacionField;
        
        private System.DateTime fechaRadicacionField;
        
        private string grupoAsignadoField;
        
        private System.DateTime fechaPromesaServicioField;
        
        private string emailField;
        
        private ServicioSalud1 servicioField;
        
        private string informacionComplementariaField;
        
        /// <remarks/>
        public string numeroRadicacion {
            get {
                return this.numeroRadicacionField;
            }
            set {
                this.numeroRadicacionField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime fechaRadicacion {
            get {
                return this.fechaRadicacionField;
            }
            set {
                this.fechaRadicacionField = value;
            }
        }
        
        /// <remarks/>
        public string grupoAsignado {
            get {
                return this.grupoAsignadoField;
            }
            set {
                this.grupoAsignadoField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime fechaPromesaServicio {
            get {
                return this.fechaPromesaServicioField;
            }
            set {
                this.fechaPromesaServicioField = value;
            }
        }
        
        /// <remarks/>
        public string email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        public ServicioSalud1 servicio {
            get {
                return this.servicioField;
            }
            set {
                this.servicioField = value;
            }
        }
        
        /// <remarks/>
        public string informacionComplementaria {
            get {
                return this.informacionComplementariaField;
            }
            set {
                this.informacionComplementariaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="ServicioSalud", Namespace="http://services.ws.autorizaciones.salud.neps.com.co/tipos")]
    public partial class ServicioSalud1 {
        
        private string codigoField;
        
        private string descripcionField;
        
        private float cantidadField;
        
        private string tipoAtencionField;
        
        /// <remarks/>
        public string codigo {
            get {
                return this.codigoField;
            }
            set {
                this.codigoField = value;
            }
        }
        
        /// <remarks/>
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
            }
        }
        
        /// <remarks/>
        public float cantidad {
            get {
                return this.cantidadField;
            }
            set {
                this.cantidadField = value;
            }
        }
        
        /// <remarks/>
        public string tipoAtencion {
            get {
                return this.tipoAtencionField;
            }
            set {
                this.tipoAtencionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.ws.autorizaciones.salud.neps.com.co/tipos")]
    public partial class Resultado {
        
        private string codigoField;
        
        private string descripcionField;
        
        /// <remarks/>
        public string codigo {
            get {
                return this.codigoField;
            }
            set {
                this.codigoField = value;
            }
        }
        
        /// <remarks/>
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.ws.autorizaciones.salud.neps.com.co/tipos")]
    public partial class Autorizacion {
        
        private string numeroAutorizacionField;
        
        private ServicioSalud1 servicioField;
        
        private string informacionComplementariaField;
        
        private Ips1 ipsField;
        
        /// <remarks/>
        public string numeroAutorizacion {
            get {
                return this.numeroAutorizacionField;
            }
            set {
                this.numeroAutorizacionField = value;
            }
        }
        
        /// <remarks/>
        public ServicioSalud1 servicio {
            get {
                return this.servicioField;
            }
            set {
                this.servicioField = value;
            }
        }
        
        /// <remarks/>
        public string informacionComplementaria {
            get {
                return this.informacionComplementariaField;
            }
            set {
                this.informacionComplementariaField = value;
            }
        }
        
        /// <remarks/>
        public Ips1 ips {
            get {
                return this.ipsField;
            }
            set {
                this.ipsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="Ips", Namespace="http://services.ws.autorizaciones.salud.neps.com.co/tipos")]
    public partial class Ips1 {
        
        private IdentificacionIps1 identificacionField;
        
        private string codigoSucursalField;
        
        /// <remarks/>
        public IdentificacionIps1 identificacion {
            get {
                return this.identificacionField;
            }
            set {
                this.identificacionField = value;
            }
        }
        
        /// <remarks/>
        public string codigoSucursal {
            get {
                return this.codigoSucursalField;
            }
            set {
                this.codigoSucursalField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="IdentificacionIps", Namespace="http://services.ws.autorizaciones.salud.neps.com.co/tipos")]
    public partial class IdentificacionIps1 {
        
        private string tipoIdentificacionField;
        
        private string numeroIdentificacionField;
        
        /// <remarks/>
        public string tipoIdentificacion {
            get {
                return this.tipoIdentificacionField;
            }
            set {
                this.tipoIdentificacionField = value;
            }
        }
        
        /// <remarks/>
        public string numeroIdentificacion {
            get {
                return this.numeroIdentificacionField;
            }
            set {
                this.numeroIdentificacionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.ws.autorizaciones.salud.neps.com.co/tipos")]
    public partial class Preautorizacion {
        
        private string numeroPreautorizacionField;
        
        private ServicioSalud1 servicioField;
        
        private string informacionComplementariaField;
        
        private Ips1 ipsField;
        
        private string nombreIPSField;
        
        private string direccionIPSField;
        
        private string telefonoIPSField;
        
        private string departamentoIPSField;
        
        private string municipioIPSField;
        
        /// <remarks/>
        public string numeroPreautorizacion {
            get {
                return this.numeroPreautorizacionField;
            }
            set {
                this.numeroPreautorizacionField = value;
            }
        }
        
        /// <remarks/>
        public ServicioSalud1 servicio {
            get {
                return this.servicioField;
            }
            set {
                this.servicioField = value;
            }
        }
        
        /// <remarks/>
        public string informacionComplementaria {
            get {
                return this.informacionComplementariaField;
            }
            set {
                this.informacionComplementariaField = value;
            }
        }
        
        /// <remarks/>
        public Ips1 ips {
            get {
                return this.ipsField;
            }
            set {
                this.ipsField = value;
            }
        }
        
        /// <remarks/>
        public string nombreIPS {
            get {
                return this.nombreIPSField;
            }
            set {
                this.nombreIPSField = value;
            }
        }
        
        /// <remarks/>
        public string direccionIPS {
            get {
                return this.direccionIPSField;
            }
            set {
                this.direccionIPSField = value;
            }
        }
        
        /// <remarks/>
        public string telefonoIPS {
            get {
                return this.telefonoIPSField;
            }
            set {
                this.telefonoIPSField = value;
            }
        }
        
        /// <remarks/>
        public string departamentoIPS {
            get {
                return this.departamentoIPSField;
            }
            set {
                this.departamentoIPSField = value;
            }
        }
        
        /// <remarks/>
        public string municipioIPS {
            get {
                return this.municipioIPSField;
            }
            set {
                this.municipioIPSField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Salida {
        
        private Preautorizacion[] preautorizacionesField;
        
        private Autorizacion[] autorizacionesField;
        
        private Resultado resultadoField;
        
        private Radicacion[] radicacionesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("preautorizaciones", Namespace="http://services.ws.autorizaciones.salud.neps.com.co/tipos")]
        public Preautorizacion[] preautorizaciones {
            get {
                return this.preautorizacionesField;
            }
            set {
                this.preautorizacionesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("autorizaciones", Namespace="http://services.ws.autorizaciones.salud.neps.com.co/tipos")]
        public Autorizacion[] autorizaciones {
            get {
                return this.autorizacionesField;
            }
            set {
                this.autorizacionesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://services.ws.autorizaciones.salud.neps.com.co/tipos")]
        public Resultado resultado {
            get {
                return this.resultadoField;
            }
            set {
                this.resultadoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("radicaciones", Namespace="http://services.ws.autorizaciones.salud.neps.com.co/tipos")]
        public Radicacion[] radicaciones {
            get {
                return this.radicacionesField;
            }
            set {
                this.radicacionesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class PersonaSolicitante {
        
        private Identificacion identificacionField;
        
        private string nombreField;
        
        private string primerApellidoField;
        
        private string segundoApellidoField;
        
        private string celularField;
        
        private string emailField;
        
        /// <remarks/>
        public Identificacion identificacion {
            get {
                return this.identificacionField;
            }
            set {
                this.identificacionField = value;
            }
        }
        
        /// <remarks/>
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
            }
        }
        
        /// <remarks/>
        public string primerApellido {
            get {
                return this.primerApellidoField;
            }
            set {
                this.primerApellidoField = value;
            }
        }
        
        /// <remarks/>
        public string segundoApellido {
            get {
                return this.segundoApellidoField;
            }
            set {
                this.segundoApellidoField = value;
            }
        }
        
        /// <remarks/>
        public string celular {
            get {
                return this.celularField;
            }
            set {
                this.celularField = value;
            }
        }
        
        /// <remarks/>
        public string email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Identificacion {
        
        private string tipoIdentificacionField;
        
        private string numeroIdentificacionField;
        
        /// <remarks/>
        public string tipoIdentificacion {
            get {
                return this.tipoIdentificacionField;
            }
            set {
                this.tipoIdentificacionField = value;
            }
        }
        
        /// <remarks/>
        public string numeroIdentificacion {
            get {
                return this.numeroIdentificacionField;
            }
            set {
                this.numeroIdentificacionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ProfesionalSalud {
        
        private IdentificacionIps identificacionField;
        
        private string nombreField;
        
        private string primerApellidoField;
        
        private string segundoApellidoField;
        
        private string especialidadField;
        
        /// <remarks/>
        public IdentificacionIps identificacion {
            get {
                return this.identificacionField;
            }
            set {
                this.identificacionField = value;
            }
        }
        
        /// <remarks/>
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
            }
        }
        
        /// <remarks/>
        public string primerApellido {
            get {
                return this.primerApellidoField;
            }
            set {
                this.primerApellidoField = value;
            }
        }
        
        /// <remarks/>
        public string segundoApellido {
            get {
                return this.segundoApellidoField;
            }
            set {
                this.segundoApellidoField = value;
            }
        }
        
        /// <remarks/>
        public string especialidad {
            get {
                return this.especialidadField;
            }
            set {
                this.especialidadField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class IdentificacionIps {
        
        private string tipoIdentificacionField;
        
        private string numeroIdentificacionField;
        
        /// <remarks/>
        public string tipoIdentificacion {
            get {
                return this.tipoIdentificacionField;
            }
            set {
                this.tipoIdentificacionField = value;
            }
        }
        
        /// <remarks/>
        public string numeroIdentificacion {
            get {
                return this.numeroIdentificacionField;
            }
            set {
                this.numeroIdentificacionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Archivo {
        
        private string nombreField;
        
        private string contenidoField;
        
        private short tipoDocumentalField;
        
        /// <remarks/>
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
            }
        }
        
        /// <remarks/>
        public string contenido {
            get {
                return this.contenidoField;
            }
            set {
                this.contenidoField = value;
            }
        }
        
        /// <remarks/>
        public short tipoDocumental {
            get {
                return this.tipoDocumentalField;
            }
            set {
                this.tipoDocumentalField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ServicioSalud {
        
        private string codigoField;
        
        private string descripcionField;
        
        private float cantidadField;
        
        private string tipoAtencionField;
        
        /// <remarks/>
        public string codigo {
            get {
                return this.codigoField;
            }
            set {
                this.codigoField = value;
            }
        }
        
        /// <remarks/>
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
            }
        }
        
        /// <remarks/>
        public float cantidad {
            get {
                return this.cantidadField;
            }
            set {
                this.cantidadField = value;
            }
        }
        
        /// <remarks/>
        public string tipoAtencion {
            get {
                return this.tipoAtencionField;
            }
            set {
                this.tipoAtencionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class GrupoTipoAtencion {
        
        private string tipoAtencionField;
        
        private ServicioSalud[] serviciosField;
        
        private Archivo[] archivosAdjuntosField;
        
        /// <remarks/>
        public string tipoAtencion {
            get {
                return this.tipoAtencionField;
            }
            set {
                this.tipoAtencionField = value;
            }
        }
        
        /// <remarks/>
        public ServicioSalud[] servicios {
            get {
                return this.serviciosField;
            }
            set {
                this.serviciosField = value;
            }
        }
        
        /// <remarks/>
        public Archivo[] archivosAdjuntos {
            get {
                return this.archivosAdjuntosField;
            }
            set {
                this.archivosAdjuntosField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Diagnostico {
        
        private string codigoField;
        
        private string descripcionField;
        
        private string tipoField;
        
        /// <remarks/>
        public string codigo {
            get {
                return this.codigoField;
            }
            set {
                this.codigoField = value;
            }
        }
        
        /// <remarks/>
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
            }
        }
        
        /// <remarks/>
        public string tipo {
            get {
                return this.tipoField;
            }
            set {
                this.tipoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Ips {
        
        private IdentificacionIps identificacionField;
        
        private string codigoSucursalField;
        
        /// <remarks/>
        public IdentificacionIps identificacion {
            get {
                return this.identificacionField;
            }
            set {
                this.identificacionField = value;
            }
        }
        
        /// <remarks/>
        public string codigoSucursal {
            get {
                return this.codigoSucursalField;
            }
            set {
                this.codigoSucursalField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void RadicarSolicitudBackOfficeCompletedEventHandler(object sender, RadicarSolicitudBackOfficeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RadicarSolicitudBackOfficeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RadicarSolicitudBackOfficeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Salida Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Salida)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591